apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zemo
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0031-tenant/tkrw-pr712-0075-0031-app/devfile-sample-zemo@sha256:4cc8bd177b9e160b4700498b61e18f2a55413d57882e3e8e5ee4fe94e3821767
        name: my-nodejs
        resources: {}
status: {}
